CREATE TABLE IF NOT EXISTS "aiOutput" (
	"id" serial PRIMARY KEY NOT NULL,
	"formData" varchar,
	"aiResponse" text,
	"templateSlug" varchar NOT NULL,
	"createdBy" varchar,
	"createdAt" varchar
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "resumes" (
	"id" serial PRIMARY KEY NOT NULL,
	"uniqueId" varchar NOT NULL,
	"content" text NOT NULL,
	"createdBy" varchar,
	"createdAt" varchar,
	"roasts" jsonb DEFAULT '[]'::jsonb
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "userResume" (
	"id" serial PRIMARY KEY NOT NULL,
	"uniqueId" varchar NOT NULL,
	"createdBy" varchar,
	"createdAt" varchar,
	"firstName" varchar,
	"lastName" varchar,
	"designation" varchar,
	"address" varchar,
	"email" varchar,
	"phone" varchar,
	"summary" text,
	"designation1" varchar,
	"companyName1" varchar,
	"city1" varchar,
	"state1" varchar,
	"startDate1" varchar,
	"endDate1" varchar,
	"description1" text,
	"designation2" varchar,
	"companyName2" varchar,
	"city2" varchar,
	"state2" varchar,
	"startDate2" varchar,
	"endDate2" varchar,
	"description2" text,
	"designation3" varchar,
	"companyName3" varchar,
	"city3" varchar,
	"state3" varchar,
	"startDate3" varchar,
	"endDate3" varchar,
	"description3" text,
	"designation4" varchar,
	"companyName4" varchar,
	"city4" varchar,
	"state4" varchar,
	"startDate4" varchar,
	"endDate4" varchar,
	"description4" text,
	"schoolName1" varchar,
	"degree1" varchar,
	"startDateEdu1" varchar,
	"endDateEdu1" varchar,
	"descriptionEdu1" text,
	"schoolName2" varchar,
	"degree2" varchar,
	"startDateEdu2" varchar,
	"endDateEdu2" varchar,
	"descriptionEdu2" text,
	"schoolName3" varchar,
	"degree3" varchar,
	"startDateEdu3" varchar,
	"endDateEdu3" varchar,
	"descriptionEdu3" text,
	"schoolName4" varchar,
	"degree4" varchar,
	"startDateEdu4" varchar,
	"endDateEdu4" varchar,
	"descriptionEdu4" text,
	"projectName1" varchar,
	"projectDescription1" text,
	"projectName2" varchar,
	"projectDescription2" text,
	"projectName3" varchar,
	"projectDescription3" text,
	"projectName4" varchar,
	"projectDescription4" text
);
