export default {
  firstName: "John",
  lastName: "Doe",
  jobTitle: "Software Engineer",
  address: "1234 Elm Street",
  phone: "123-456-7890",
  email: "youremail@gmail.com",
  themeColor: "#2962ff",
  summary: "Lorem ipsum dolor sit amet, consectetur adipiscing elit",
  experience: [
    {
      id: 1,
      title: "Software Engineer",
      company: "Google",
      city: "Mountain View, CA",
      state: "California",
      startDate: "Mar 2019",
      endDate: "",
      currentlyWorking: true,
      workSummary: "Lorem ipsum dolor sit amet, consectetur adipiscing elit",
    },
    {
      id: 2,
      title: "Software Engineer",
      company: "Facebook",
      city: "Menlo Park, CA",
      state: "California",
      startDate: "Jan 2017",
      endDate: "Feb 2019",
      currentlyWorking: false,
      workSummary: "Lorem ipsum dolor sit amet, consectetur adipiscing elit",
    },
  ],
  education: [
    {
      id: 1,
      universityName: "Stanford University",
      startDate: "2013-01-01",
      endDate: "2017-01-01",
      degree: "Bachelor of Science",
      major: "Computer Science",
      description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit",
    },
    {
      id: 2,
      universityName: "Stanford University",
      startDate: "2017-01-01",
      endDate: "2019-01-01",
      degree: "Master of Science",
      major: "Computer Science",
      description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit",
    },
  ],
  projects: [
    // Add this field
    {
      id: 1,
      title: "Project One",
      description: "Description of project one",
      startDate: "2022-01-01",
      endDate: "2022-12-31",
    },
    {
      id: 2,
      title: "Project Two",
      description: "Description of project two",
      startDate: "2021-06-01",
      endDate: "2021-12-31",
    },
  ],
  skills: "Python, Java, JavaScript, HTML, CSS, Node.js",
};
